### ISSUE TITLE
Inputbox after Tags

### ISSUE THREAD

**Issue by Amerlander** [sciactive/ptags#3]
Is it posible to generate the Tags in front of the Textbox?

Tag | Tag | Tag | Tag
Tag | Tag | Tag | Inputfield

Instead off

Inputfield | Tag | Tag | Tag
Tag | Tag | Tag | Tag

**Comment by Amerlander** [comment]
It would be even better if I could change the order of new Tags:

Inputfield | NEW Tag | Old Tag | Old Tag

So new tags go between the Input and the other Tags and on 1. position in the String.

Instead of:

Inputfield | Old Tag | Old Tag | New Tag

**Comment by hperrin** [comment]
Archiving repo.
